# Generated by Django 5.2.14 on 2026-06-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_all_delete_mine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='all',
            options={'ordering': ['published_date'], 'verbose_name_plural': 'for mine workouts'},
        ),
        migrations.RemoveField(
            model_name='all',
            name='text',
        ),
        migrations.AddField(
            model_name='all',
            name='content',
            field=models.TextField(null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='all',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True,null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all',
            name='published_date',
            field=models.DateTimeField(null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='all',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='all',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
