# Generated by Django 5.2.14 on 2026-06-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_alter_all_options_remove_all_text_all_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(null=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'for mine workouts',
                'ordering': ['published_date'],
            },
        ),
        migrations.DeleteModel(
            name='all',
        ),
    ]
