# Generated by Django 5.2.14 on 2026-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_mine_delete_all'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mine',
            options={'ordering': ['-published_date'], 'verbose_name_plural': 'for mine workouts'},
        ),
        migrations.AddField(
            model_name='mine',
            name='counted_view',
            field=models.IntegerField(default=0),
        ),
    ]
